owner: musosys
repo: status

sites:
  - name: Musonet Cloud
    url: https://musonet.cloud

status-website:
  baseUrl: /status
  logoUrl: https://prod-assets.musonet.cloud/media/dark_color_main_logo02.png
  name: Musonet Cloud Status
  introTitle: "**Musonet Cloud Status**"
  introMessage: Real-time uptime monitoring for Musonet Cloud services, powered by GitHub Actions.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
