owner: musosys
repo: status

sites:
  - name: Musonet Cloud
    url: https://musonet.cloud
    expectedStatus: 403

status-website:
  baseUrl: /status
  logoUrl: https://prod-assets.musonet.cloud/media/dark_color_main_logo02.png
  name: " "
  introTitle: ""
  introMessage: Real-time uptime monitoring for Musonet Cloud services, powered by GitHub Actions.
  navbar:
    - title: Status
      href: https://musosys.github.io/status
    - title: Main Site
      href: https://musonet.cloud
      newTab: true
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
      newTab: true

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
